package:
  format-version: "1.0.0"
  name: "wireless_system_rnwf"
  type: "api"
  status: "production"
  required: false
  version: "v2.0.0"
  
  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.18.5"
    - name: "core"
      type: "package"
      version: "v3.13.4"
    - name: "bsp"
      type: "package"
      version: "v3.17.0"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.11.0"

