package:
  format-version: "1.0.0"
  name: "wireless_system_rnwf"
  type: "api"
  status: "production"
  required: false
  version: "v3.2.0"
  
  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.25.2"
    - name: "core"
      type: "package"
      version: "v3.16.3"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.13.0"

