/* WINCS02  WIFI System Service Configuration Options */

<#if SYS_RNWF_WIFI_MODE == "STA">
#define SYS_WINCS_WIFI_DEVMODE        		SYS_WINCS_WIFI_MODE_STA
<#elseif SYS_RNWF_WIFI_MODE == "AP">
#define SYS_WINCS_WIFI_DEVMODE        		SYS_WINCS_WIFI_MODE_AP
</#if>

<#if SYS_RNWF_WIFI_MODE_STA == true>
#define SYS_WINCS_WIFI_STA_SSID				"${SYS_RNWF_WIFI_STA_SSID_NAME}"
#define SYS_WINCS_WIFI_STA_PWD        		"${SYS_RNWF_WIFI_STA_PWD_NAME}"
<#if SYS_RNWF_WIFI_STA_SECURITY == "OPEN">
#define SYS_WINCS_STA_SECURITY				SYS_WINCS_OPEN
<#elseif SYS_RNWF_WIFI_STA_SECURITY == "WPA2">
#define SYS_WINCS_STA_SECURITY				SYS_WINCS_WPA2 
<#elseif SYS_RNWF_WIFI_STA_SECURITY == "RSVD">
#define SYS_WINCS_STA_SECURITY				SYS_WINCS_RSVD
<#elseif SYS_RNWF_WIFI_STA_SECURITY == "WPA3">
#define SYS_WINCS_STA_SECURITY				SYS_WINCS_WPA3
<#elseif SYS_RNWF_WIFI_STA_SECURITY == "WPA2-MIXED">
#define SYS_WINCS_STA_SECURITY				SYS_WINCS_WPA2_MIXED
<#elseif SYS_RNWF_WIFI_STA_SECURITY == "WPA3-TRANS">
#define SYS_WINCS_STA_SECURITY				SYS_WINCS_WPA3_TRANS
</#if>
<#if SYS_RNWF_WIFI_STA_AUTOCONNECT == true>
#define SYS_WINCS_WIFI_STA_AUTOCONNECT   	true
<#else>
#define SYS_WINCS_WIFI_STA_AUTOCONNECT   	false
</#if>
</#if>

<#if SYS_RNWF_WIFI_MODE_AP == true>
#define SYS_WINCS_WIFI_AP_SSID				"${SYS_RNWF_WIFI_AP_SSID_NAME}"
#define SYS_WINCS_WIFI_AP_PWD        		"${SYS_WIFI_AP_PWD_NAME}"
<#if SYS_RNWF_WIFI_AP_SECURITY == "OPEN">
#define SYS_WINCS_SOFT_AP_SECURITY			SYS_WINCS_OPEN
<#elseif SYS_RNWF_WIFI_AP_SECURITY == "WPA2">
#define SYS_WINCS_SOFT_AP_SECURITY			SYS_WINCS_WPA2
<#elseif SYS_RNWF_WIFI_AP_SECURITY == "RSVD">
#define SYS_WINCS_SOFT_AP_SECURITY			SYS_WINCS_RSVD
<#elseif SYS_RNWF_WIFI_AP_SECURITY == "WPA2_MIXED">
#define SYS_WINCS_SOFT_AP_SECURITY			SYS_WINCS_WPA2_MIXED
<#elseif SYS_RNWF_WIFI_AP_SECURITY == "WPA3">
#define SYS_WINCS_SOFT_AP_SECURITY			SYS_WINCS_WPA3
<#elseif SYS_RNWF_WIFI_AP_SECURITY == "WPA3_TRANS">
#define SYS_WINCS_SOFT_AP_SECURITY			SYS_WINCS_WPA3_TRANS
</#if>
#define SYS_WINCS_WIFI_CHANNEL              ${SYS_RNWF_WIFI_AP_CHANNEL}
</#if>

<#if SYS_RNWF_WIFI_MODE_PROV == true>
#define SYS_WINCS_WIFI_PROV_SSID			"${SYS_RNWF_WIFI_PROV_SSID_NAME}"
#define SYS_WINCS_WIFI_PROV_PWD        		"${SYS_WIFI_PROV_PWD_NAME}"
<#if SYS_RNWF_WIFI_PROV_SECURITY == "OPEN">
#define SYS_WINCS_PROV_SECURITY				SYS_WINCS_OPEN
<#elseif SYS_RNWF_WIFI_PROV_SECURITY == "WPA2">
#define SYS_WINCS_PROV_SECURITY				SYS_WINCS_WPA2
<#elseif SYS_RNWF_WIFI_PROV_SECURITY == "RSVD">
#define SYS_WINCS_PROV_SECURITY				SYS_WINCS_RSVD
<#elseif SYS_RNWF_WIFI_PROV_SECURITY == "WPA2_MIXED">
#define SYS_WINCS_PROV_SECURITY				SYS_WINCS_WPA2_MIXED
<#elseif SYS_RNWF_WIFI_PROV_SECURITY == "WPA3">
#define SYS_WINCS_PROV_SECURITY				SYS_WINCS_WPA3
<#elseif SYS_RNWF_WIFI_PROV_SECURITY == "WPA3_TRANS">
#define SYS_WINCS_PROV_SECURITY				SYS_WINCS_WPA3_TRANS
</#if>
<#if SYS_RNWF_WIFI_PROV_METHOD == "PROV_WEB_SERVER">
#define SYS_WINCS_PROVI_WEB_SERVER			1
<#elseif SYS_RNWF_WIFI_PROV_METHOD == "PROV_MOBILE_APP">
#define SYS_WINCS_PROVI_MOBILE_APP			1
</#if>
#define SYS_WINCS_WIFI_CHANNEL               ${SYS_RNWF_WIFI_PROV_CHANNEL}
</#if>
#define SYS_WINCS_COUNTRYCODE                ${SYS_RNWF_COUNTRYCODE}
<#if SYS_RNWF_WIFI_DEBUG_LOGS == true>
#define SYS_WINCS_WIFI_DEBUG_LOGS            1
</#if>
<#if SYS_RNWF_WIFI_BT_COEXIST == true>
#define SYS_WINCS_WIFI_BT_COEXIST            1
<#if SYS_RNWF_INF_TYPE == "3-wire">
#define SYS_WINCS_WIFI_BT_INF_2WIRE          false
<#elseif SYS_RNWF_INF_TYPE == "2-wire">
#define SYS_WINCS_WIFI_BT_INF_2WIRE          true
</#if>
<#if SYS_RNWF_WLAN_RX_PRIO == true>
#define SYS_WINCS_WLAN_RX_PRIO               true
<#else>
#define SYS_WINCS_WLAN_RX_PRIO               false
</#if>
<#if SYS_RNWF_WLAN_TX_PRIO == true>
#define SYS_WINCS_WLAN_TX_PRIO               true
<#else>
#define SYS_WINCS_WLAN_TX_PRIO               false
</#if>
<#if SYS_RNWF_INTENNA_TYPE == "Dedicated Antenna">
#define SYS_WINCS_ANTENNA_TYPE_SHARED        false
<#elseif SYS_RNWF_INTENNA_TYPE == "Shared Antenna">
#define SYS_WINCS_ANTENNA_TYPE_SHARED        true
</#if>
</#if>
<#if SYS_RNWF_POWER_SAVE_MODE == true>
#define SYS_WINCS_POWER_SAVE_MODE            1
</#if>
<#if SYS_RNWF_SNTP_ADDRESS != "">
#define SYS_WINCS_SNTP_ADDRESS               ${SYS_RNWF_SNTP_ADDRESS}
</#if>

<#if SYS_RNWF_PING == true>
#define SYS_WINCS_PING_ADDRESS               "${SYS_RNWF_PING_ADDRESS}"
</#if>

#define SYS_WINCS_WIFI_AP_IP_ADDR            "192.168.0.0"
#define SYS_WINCS_WIFI_AP_IP_POOL_START      "192.168.0.1"
#define SYS_WINCS_WIFI_CallbackHandler	     ${SYS_RNWF_WIFI_CALLBACK_HANDLER}