<#if SYS_RNWF_MQTT_VERSION == "v3.1.1">
#define SYS_RNWF_MQTT_VERSION                   3
<#else>
#define SYS_RNWF_MQTT_VERSION                   5
#define SYS_RNWF_MQTT_SESSION_EXP_INTERVAL     ${SYS_RNWF_MQTT_SESSION_EXP_INT}
</#if>

#define SYS_RNWF_MQTT_CLOUD_URL         		"${SYS_RNWF_MQTT_CLOUD_URL}"
#define SYS_RNWF_MQTT_CLOUD_PORT			    ${SYS_RNWF_MQTT_CLOUD_PORT}
#define SYS_RNWF_MQTT_CLIENT_ID       			"${SYS_RNWF_MQTT_CLIENT_ID}"
#define SYS_RNWF_MQTT_CLOUD_USER_NAME			"${SYS_RNWF_MQTT_CLOUD_USER_NAME}"
#define SYS_RNWF_MQTT_PASSWORD				    "${SYS_RNWF_MQTT_PASSWORD}"

<#if SYS_RNWF_MQTT_KEEP_ALIVE == true>
#define SYS_RNWF_MQTT_KEEP_ALIVE_INT            ${SYS_RNWF_MQTT_KEEP_ALIVE_INT}
</#if>

<#if SYS_RNWF_MQTT_LWT_ENABLE == true >
#define SYS_RNWF_MQTT_LWT_MESSAGE               "${SYS_RNWF_MQTT_LWT_MESSAGE}"
</#if>

<#if  SYS_RNWF_MQTT_SUBSCRIBE == true >
<#if  SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 1 > 
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_0_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS0}

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 2 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_0_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS0}
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS1}

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 3 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_0_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS0}
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS1}
#define SYS_RNWF_MQTT_SUB_TOPIC_2            "${SYS_RNWF_MQTT_SUB_TOPIC2}"
#define SYS_RNWF_MQTT_SUB_TOPIC_2_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS2}

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 4 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_0_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS0}
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS1}
#define SYS_RNWF_MQTT_SUB_TOPIC_2            "${SYS_RNWF_MQTT_SUB_TOPIC2}"
#define SYS_RNWF_MQTT_SUB_TOPIC_2_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS2}
#define SYS_RNWF_MQTT_SUB_TOPIC_3            "${SYS_RNWF_MQTT_SUB_TOPIC3}"
#define SYS_RNWF_MQTT_SUB_TOPIC_3_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS3}

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 5 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_0_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS0}
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS1}
#define SYS_RNWF_MQTT_SUB_TOPIC_2            "${SYS_RNWF_MQTT_SUB_TOPIC2}"
#define SYS_RNWF_MQTT_SUB_TOPIC_2_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS2}
#define SYS_RNWF_MQTT_SUB_TOPIC_3            "${SYS_RNWF_MQTT_SUB_TOPIC3}"
#define SYS_RNWF_MQTT_SUB_TOPIC_3_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS3}
#define SYS_RNWF_MQTT_SUB_TOPIC_4            "${SYS_RNWF_MQTT_SUB_TOPIC4}"
#define SYS_RNWF_MQTT_SUB_TOPIC_4_QOS        SYS_RNWF_MQTT_${SYS_RNWF_MQTT_SUB_TOPIC_QOS4}
</#if>
</#if>

<#if SYS_RNWF_MQTT_PUBLISH == true>
#define SYS_RNWF_MQTT_PUB_TOPIC_NAME        "${SYS_RNWF_MQTT_PUB_TOPIC_NAME}"
#define SYS_RNWF_MQTT_PUB_MSG               "${SYS_RNWF_MQTT_PUB_MSG}"
#define SYS_RNWF_MQTT_PUB_QOS_TYPE          SYS_RNWF_MQTT_${SYS_RNWF_MQTT_PUB_QOS_TYPE}
<#if SYS_RNWF_MQTT_RETAIN_FLAG == false>
#define SYS_RNWF_MQTT_RETAIN_TYPE			SYS_RNWF_NO_RETAIN
<#else>
#define SYS_RNWF_MQTT_RETAIN_TYPE			SYS_RNWF_RETAIN
</#if>
</#if>

<#if SYS_RNWF_MQTT_TX_PROP == true>
#define SYS_RNWF_MQTT_PAYLOD_FORMAT_IND     ${SYS_RNWF_MQTT_PAYLOD_FORMAT_IND}
#define SYS_RNWF_MQTT_MSG_EXP_INT           ${SYS_RNWF_MQTT_MSG_EXP_INT}
#define SYS_RNWF_MQTT_CONTENT_TYPE          "${SYS_RNWF_MQTT_CONTENT_TYPE}"
<#if SYS_MQTT_USER_PROP == true>
#define SYS_RNWF_MQTT_PUB_MSG_USER_PROP_KEY    "${SYS_MQTT_USER_PROP_KEY}"
#define SYS_RNWF_MQTT_PUB_MSG_USER_PROP_VALUE  "${SYS_MQTT_USER_PROP_VALUE}"
</#if>
</#if>

<#if SYS_MQTT_ENABLE_TLS == true >
#define SYS_RNWF_MQTT_TLS_ENABLE          "1"

<#if SYS_MQTT_ENABLE_PEER_AUTH == true>
#define SYS_MQTT_ENABLE_PEER_AUTH         "1"
#define SYS_RNWF_MQTT_SERVER_CERT         "${SYS_RNWF_MQTT_SERVER_CERT}"
<#else>
#define SYS_MQTT_ENABLE_PEER_AUTH         NULL
</#if>
<#if SYS_RNWF_MQTT_DEVICE_CERT == "" >
#define SYS_RNWF_MQTT_DEVICE_CERT               NULL
<#else>
#define SYS_RNWF_MQTT_DEVICE_CERT               "${SYS_RNWF_MQTT_DEVICE_CERT}"
</#if>
<#if SYS_RNWF_MQTT_DEVICE_KEY == "">
#define SYS_RNWF_MQTT_DEVICE_KEY                NULL
<#else>
#define SYS_RNWF_MQTT_DEVICE_KEY                "${SYS_RNWF_MQTT_DEVICE_KEY}"
</#if>
<#if SYS_RNWF_MQTT_DEVICE_KEY_PSK == "" >
#define SYS_RNWF_MQTT_DEVICE_KEY_PSK            NULL
<#else>
#define SYS_RNWF_MQTT_DEVICE_KEY_PSK            "${SYS_RNWF_MQTT_DEVICE_KEY_PSK}"
</#if>
<#if SYS_RNWF_MQTT_TLS_SERVER_NAME == "" >
#define SYS_RNWF_MQTT_TLS_SERVER_NAME           NULL
<#else>
#define SYS_RNWF_MQTT_TLS_SERVER_NAME           "${SYS_RNWF_MQTT_TLS_SERVER_NAME}"
</#if>
<#if SYS_MQTT_DOMAIN_NAME_VERIFY == true >
#define SYS_MQTT_DOMAIN_NAME_VERIFY             "1"
#define SYS_RNWF_MQTT_TLS_DOMAIN_NAME           "${SYS_RNWF_MQTT_TLS_DOMAIN_NAME}"
<#else>
#define SYS_MQTT_DOMAIN_NAME_VERIFY             NULL
#define SYS_RNWF_MQTT_TLS_DOMAIN_NAME           NULL
</#if>

<#else>
#define SYS_RNWF_MQTT_TLS_ENABLE                false
</#if>

<#if SYS_RNWF_MQTT_AZURE_DPS_ENABLE == true >
#define SYS_RNWF_MQTT_AZURE_DPS_ENABLE			 true
#define SYS_RNWF_MQTT_SCOPE_ID       			 "${SYS_RNWF_MQTT_SCOPE_ID}"
#define SYS_RNWF_MQTT_DEVICE_TEMPLATE			 "${SYS_RNWF_MQTT_DEVICE_TEMPLATE}"
<#else>
#define SYS_RNWF_MQTT_AZURE_DPS_ENABLE			 false
</#if>
<#if SYS_RNWF_MQTT_DEBUG_LOGS == true>
#define SYS_RNWF_MQTT_DEBUG_LOGS                 1
</#if>
#define SYS_RNWF_MQTT_CallbackHandler            ${SYS_RNWF_MQTT_CALLBACK_HANDLER}