#define SYS_RNWF_MQTT_CLOUD_URL        		    "${SYS_RNWF_MQTT_CLOUD_URL}"
#define SYS_RNWF_MQTT_CLOUD_PORT			    ${SYS_RNWF_MQTT_CLOUD_PORT}
<#if SYS_RNWF_MQTT_AZURE_DPS_ENABLE == true>
#define SYS_RNWF_MQTT_AZURE_DPS_ENABLE			1
#define SYS_RNWF_MQTT_SCOPE_ID       			"${SYS_RNWF_MQTT_SCOPE_ID}"
#define SYS_RNWF_MQTT_DEVICE_TEMPLATE			"${SYS_RNWF_MQTT_DEVICE_TEMPLATE}"
<#elseif SYS_RNWF_MQTT_AZURE_DPS_ENABLE == false >
#define SYS_RNWF_MQTT_AZURE_DPS_ENABLE			    0
</#if>
#define SYS_RNWF_MQTT_CLOUD_USER_NAME			"${SYS_RNWF_MQTT_CLOUD_USER_NAME}"
#define SYS_RNWF_MQTT_PASSWORD				    "${SYS_RNWF_MQTT_PASSWORD}"
#define SYS_RNWF_MQTT_CLIENT_ID       			"${SYS_RNWF_MQTT_CLIENT_ID}"
<#if SYS_RNWF_MQTT_VERSION == "V3.1.1">
#define SYS_RNWF_MQTT_VERSION                   3
<#else>
#define SYS_RNWF_MQTT_VERSION                   5
</#if>
<#if SYS_RNWF_MQTT_AZURE_PUBLISH == true>
#define SYS_RNWF_MQTT_TOPIC_NAME        	    "${SYS_RNWF_MQTT_PUB_TOPIC_NAME}"
<#if SYS_RNWF_MQTT_QOS_TYPE == "QOS0">
#define SYS_RNWF_MQTT_QOS_TYPE					SYS_RNWF_MQTT_QOS0
<#elseif SYS_RNWF_MQTT_QOS_TYPE == "QOS1">
#define SYS_RNWF_MQTT_QOS_TYPE					SYS_RNWF_MQTT_QOS1
<#elseif SYS_RNWF_MQTT_QOS_TYPE == "QOS2">
#define SYS_RNWF_MQTT_QOS_TYPE					SYS_RNWF_MQTT_QOS2
</#if>
<#if SYS_RNWF_MQTT_AZURE_RETAIN_FLAG == false>
#define SYS_RNWF_MQTT_RETAIN_TYPE				SYS_RNWF_NO_RETAIN
<#else>
#define SYS_RNWF_MQTT_RETAIN_TYPE				SYS_RNWF_RETAIN
</#if>
</#if>
<#if SYS_RNWF_MQTT_AZURE_KEEP_ALIVE == true>
#define SYS_RNWF_MQTT_KEEP_ALIVE_INT            ${SYS_RNWF_MQTT_KEEP_ALIVE_INT}
</#if>
<#if  SYS_RNWF_MQTT_AZURE_SUBSCRIBE == true >
<#if  SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 1 > 
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_QOS_TYPE           "${SYS_RNWF_MQTT_SUB_QOS_TYPE}"

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 2 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_QOS_TYPE           "${SYS_RNWF_MQTT_SUB_QOS_TYPE}"

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 3 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_TOPIC_2            "${SYS_RNWF_MQTT_SUB_TOPIC2}"
#define SYS_RNWF_MQTT_SUB_QOS_TYPE           "${SYS_RNWF_MQTT_SUB_QOS_TYPE}"

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 4 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_TOPIC_2            "${SYS_RNWF_MQTT_SUB_TOPIC2}"
#define SYS_RNWF_MQTT_SUB_TOPIC_3            "${SYS_RNWF_MQTT_SUB_TOPIC3}"
#define SYS_RNWF_MQTT_SUB_QOS_TYPE           "${SYS_RNWF_MQTT_SUB_QOS_TYPE}"

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 5 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_TOPIC_2            "${SYS_RNWF_MQTT_SUB_TOPIC2}"
#define SYS_RNWF_MQTT_SUB_TOPIC_3            "${SYS_RNWF_MQTT_SUB_TOPIC3}"
#define SYS_RNWF_MQTT_SUB_TOPIC_4            "${SYS_RNWF_MQTT_SUB_TOPIC4}"
#define SYS_RNWF_MQTT_SUB_QOS_TYPE           "${SYS_RNWF_MQTT_SUB_QOS_TYPE}"
</#if>
</#if>
<#if SYS_MQTT_AZURE_ENABLE_TLS == true >
<#if SYS_MQTT_AZURE_ENABLE_PEER_AUTH == true >
#define SYS_MQTT_AZURE_ENABLE_PEER_AUTH       "1"
#define SYS_RNWF_MQTT_SERVER_CERT            "${SYS_RNWF_MQTT_SERVER_CERT}"
<#else>
#define SYS_MQTT_AZURE_ENABLE_PEER_AUTH       NULL
</#if>

<#if SYS_RNWF_MQTT_DEVICE_CERT == "" >
#define SYS_RNWF_MQTT_DEVICE_CERT           NULL
<#else>
#define SYS_RNWF_MQTT_DEVICE_CERT            "${SYS_RNWF_MQTT_DEVICE_CERT}"
</#if>
<#if SYS_RNWF_MQTT_DEVICE_KEY == "">
#define SYS_RNWF_MQTT_DEVICE_KEY            NULL
<#else>
#define SYS_RNWF_MQTT_DEVICE_KEY             "${SYS_RNWF_MQTT_DEVICE_KEY}"
</#if>
<#if SYS_RNWF_MQTT_DEVICE_KEY_PSK == "" >
#define SYS_RNWF_MQTT_DEVICE_KEY_PSK         NULL
<#else>
#define SYS_RNWF_MQTT_DEVICE_KEY_PSK         "${SYS_RNWF_MQTT_DEVICE_KEY_PSK}"
</#if>

<#if SYS_RNWF_MQTT_TLS_SERVER_NAME == "" >
#define SYS_RNWF_MQTT_TLS_SERVER_NAME        NULL
<#else>
#define SYS_RNWF_MQTT_TLS_SERVER_NAME        "${SYS_RNWF_MQTT_TLS_SERVER_NAME}"
</#if>
<#if SYS_MQTT_AZURE_DOMAIN_NAME_VERIFY == true >
#define SYS_MQTT_AZURE_DOMAIN_NAME_VERIFY    "1"
#define SYS_RNWF_MQTT_TLS_DOMAIN_NAME        "${SYS_RNWF_MQTT_TLS_DOMAIN_NAME}"
<#else>
#define SYS_MQTT_AZURE_DOMAIN_NAME_VERIFY    NULL
</#if>
<#elseif SYS_RNWF_MQTT_AZURE_DPS_ENABLE == false >
#define SYS_MQTT_AZURE_ENABLE_TLS			    0
</#if>
<#if SYS_RNWF_MQTT_DEBUG_LOGS == true>
#define SYS_RNWF_MQTT_DEBUG_LOGS                1
</#if>
#define SYS_RNWF_MQTT_CallbackHandler           ${SYS_RNWF_MQTT_CALLBACK_HANDLER}