
/* WINCS02  OTA System Service Configuration Options */
/* OTA- Configuration Socket  */

#define SYS_RNWF_OTA_CONF_SOCK_BIND_TYPE	          SYS_RNWF_NET_BIND_TYPE${SYS_RNWF_OTA_CONF_SOC}
#define SYS_RNWF_OTA_CONF_SOCK_TYPE	                  SYS_RNWF_NET_SOCK_TYPE${SYS_RNWF_OTA_CONF_SOC}  
#define SYS_RNWF_OTA_CONF_SOCK_PORT		              SYS_RNWF_NET_SOCK_PORT${SYS_RNWF_OTA_CONF_SOC} 
#define SYS_RNWF_OTA_CONF_SOCK_TYPE_IPv4              SYS_RNWF_NET_SOCK_TYPE_IPv4_${SYS_RNWF_OTA_CONF_SOC}
#define SYS_RNWF_OTA_CONF_SOCK_TYPE_IPv6_LOCAL        SYS_RNWF_NET_SOCK_TYPE_IPv6_LOCAL${SYS_RNWF_OTA_CONF_SOC}
#define SYS_RNWF_OTA_CONF_SOCK_TYPE_IPv6_GLOBAL       SYS_RNWF_NET_SOCK_TYPE_IPv6_GLOBAL${SYS_RNWF_OTA_CONF_SOC}
#define SYS_RNWF_OTA_CONF_SOCK_TLS_ENABLE		      SYS_RNWF_TLS_ENABLE${SYS_RNWF_OTA_CONF_SOC}	
/* OTA- Server Socket Configuration */

#define SYS_RNWF_OTA_SERV_SOCK_BIND_TYPE	          SYS_RNWF_NET_BIND_TYPE${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_TYPE	                  SYS_RNWF_NET_SOCK_TYPE${SYS_RNWF_OTA_SERVER_SOC}  
#define SYS_RNWF_OTA_SERV_SOCK_PORT		              SYS_RNWF_NET_SOCK_PORT${SYS_RNWF_OTA_SERVER_SOC} 
#define SYS_RNWF_OTA_SERV_SOCK_TYPE_IPv4              SYS_RNWF_NET_SOCK_TYPE_IPv4_${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_TYPE_IPv6_LOCAL        SYS_RNWF_NET_SOCK_TYPE_IPv6_LOCAL${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_TYPE_IPv6_GLOBAL       SYS_RNWF_NET_SOCK_TYPE_IPv6_GLOBAL${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_TLS_ENABLE             SYS_RNWF_TLS_ENABLE${SYS_RNWF_OTA_SERVER_SOC}

<#assign otaServerSoc = SYS_RNWF_OTA_SERVER_SOC> 
<#assign tlsVariableName = "sysNetRNWF.SYS_RNWF_NET_ENABLE_TLS" + otaServerSoc>
<#assign otaServSocTlsEnable = tlsVariableName?eval>
<#if otaServSocTlsEnable == true >
#define SYS_RNWF_OTA_SERV_SOCK_PEER_AUTH	          SYS_RNWF_NET_PEER_AUTH${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_ROOT_CERT	          SYS_RNWF_NET_ROOT_CERT${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_DEV_CERT	              SYS_RNWF_NET_DEVICE_CERTIFICATE${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_DEV_KEY	              SYS_RNWF_NET_DEVICE_KEY${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_DEV_KEY_PWD	          SYS_RNWD_NET_DEVICE_KEY_PWD${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_SERVER_NAME            SYS_RNWF_NET_SERVER_NAME${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_DOMAIN_NAME_VERIFY	  SYS_RNWF_NET_DOMAIN_NAME_VERIFY${SYS_RNWF_OTA_SERVER_SOC}
#define SYS_RNWF_OTA_SERV_SOCK_DOMAIN_NAME	          SYS_RNWF_NET_DOMAIN_NAME${SYS_RNWF_OTA_SERVER_SOC}
</#if>

#define SYS_RNWF_OTA_FLASH_START_ADDRESS              ${SYS_RNWF_OTA_FLASH_ADDR}
#define SYS_RNWF_OTA_CallbackHandler   		   	      ${SYS_RNWF_OTA_CALLBACK_HANDLER}
