
/* WINCS02  OTA System Service Configuration Options */

/* OTA- Server Socket Configuration */
<#if SYS_WINCS_DIRECT_OTA_ENABLE == true >
#define SYS_WINCS_OTA_SERV_SOCK_BIND_TYPE	          SYS_WINCS_NET_BIND_TYPE${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_TYPE	              SYS_WINCS_NET_SOCK_TYPE${SYS_WINCS_OTA_SERVER_SOC}  
#define SYS_WINCS_OTA_SERV_SOCK_PORT		          SYS_WINCS_NET_SOCK_PORT${SYS_WINCS_OTA_SERVER_SOC} 
#define SYS_WINCS_OTA_SERV_SOCK_TYPE_IPv4             SYS_WINCS_NET_SOCK_TYPE_IPv4_${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_TYPE_IPv6_LOCAL       SYS_WINCS_NET_SOCK_TYPE_IPv6_LOCAL${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_TYPE_IPv6_GLOBAL      SYS_WINCS_NET_SOCK_TYPE_IPv6_GLOBAL${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_TLS_ENABLE            SYS_WINCS_TLS_ENABLE${SYS_WINCS_OTA_SERVER_SOC}

#define SYS_WINCS_OTA_FILE_NAME                       "${SYS_WINCS_OTA_FILE_NAME}"
#define SYS_WINCS_OTA_TIMEOUT                         ${SYS_WINCS_OTA_TIME_OUT}
</#if>
<#assign otaServerSoc = SYS_WINCS_OTA_SERVER_SOC> 
<#assign tlsVariableName = "sysNetRNWF.SYS_RNWF_NET_ENABLE_TLS" + otaServerSoc>
<#assign otaServSocTlsEnable = tlsVariableName?eval>
<#if otaServSocTlsEnable == true >
#define SYS_WINCS_OTA_SERV_SOCK_PEER_AUTH	          SYS_WINCS_NET_PEER_AUTH${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_ROOT_CERT	          SYS_WINCS_NET_ROOT_CERT${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_DEV_CERT	          SYS_WINCS_NET_DEVICE_CERTIFICATE${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_DEV_KEY	              SYS_WINCS_NET_DEVICE_KEY${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_DEV_KEY_PWD	          SYS_WINCS_NET_DEVICE_KEY_PWD${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_SERVER_NAME           SYS_WINCS_NET_SERVER_NAME${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_DOMAIN_NAME_VERIFY	  SYS_WINCS_NET_DOMAIN_NAME_VERIFY${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_SERV_SOCK_DOMAIN_NAME	          SYS_WINCS_NET_DOMAIN_NAME${SYS_WINCS_OTA_SERVER_SOC}
#define SYS_WINCS_OTA_TLS_ENABLE                      true    
#define SYS_WINCS_TLS_OTA_URL                         "https://%s:%d/%s"   
<#else> 
#define SYS_WINCS_OTA_TLS_ENABLE                      NULL
#define SYS_WINCS_OTA_URL                             "http://%s:%d/%s"
</#if>

#define SYS_WINCS_OTA_CallbackHandler   		   	      ${SYS_RNWF_OTA_CALLBACK_HANDLER}
