/* WINCS02  NET System Service Configuration Options */

<#if SYS_RNWF_NET_SOCK_CONF == true>

<#if SYS_RNWF_NET_MODE0 == "SERVER">
#define SYS_WINCS_NET_BIND_TYPE0				SYS_WINCS_BIND_LOCAL
<#elseif SYS_RNWF_NET_MODE0 == "CLIENT">
#define SYS_WINCS_NET_BIND_TYPE0				SYS_WINCS_BIND_REMOTE 
</#if>
<#if SYS_RNWF_NET_SOCK_TYPE0 == "UDP">
#define SYS_WINCS_NET_SOCK_TYPE0				SYS_WINCS_SOCK_UDP
<#elseif SYS_RNWF_NET_SOCK_TYPE0 == "TCP">
#define SYS_WINCS_NET_SOCK_TYPE0				SYS_WINCS_SOCK_TCP 
</#if>
<#if SYS_RNWF_NET_SOCK_IP_TYPE0 == "IPv4">
#define SYS_WINCS_NET_SOCK_TYPE_IPv4_0           4
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_LOCAL0      0
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_GLOBAL0     0
<#elseif SYS_RNWF_NET_SOCK_IP_TYPE0 == "IPv6 Local">
#define SYS_WINCS_NET_SOCK_TYPE_IPv4_0           0
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_LOCAL0      6
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_GLOBAL0     0
<#elseif SYS_RNWF_NET_SOCK_IP_TYPE0 == "IPv6 Global">
#define SYS_WINCS_NET_SOCK_TYPE_IPv4_0           0
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_LOCAL0      0
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_GLOBAL0     6
</#if>
<#if SYS_RNWF_NET_MODE0 == "CLIENT">
#define SYS_WINCS_NET_SOCK_SERVER_ADDR0         "${SYS_RNWF_NET_SOCK_IP_ADDR0}"
</#if>
#define SYS_WINCS_NET_SOCK_PORT0				${SYS_RNWF_NET_SOCK_PORT0}
<#if SYS_RNWF_NET_ENABLE_TLS0 == true >
#define SYS_WINCS_TLS_ENABLE0					1
#define SYS_WINCS_NET_ROOT_CERT0				"${SYS_RNWF_NET_ROOT_CERT0}"
<#if SYS_RNWF_NET_DEVICE_KEY0 == "" >
#define SYS_WINCS_NET_DEVICE_KEY0				NULL
<#else>
#define SYS_WINCS_NET_DEVICE_KEY0				"${SYS_RNWF_NET_DEVICE_KEY0}"
</#if>
<#if SYS_RNWD_NET_DEVICE_KEY_PWD0 == "" >
#define SYS_RNWD_NET_DEVICE_KEY_PWD0			NULL
<#else>
#define SYS_RNWD_NET_DEVICE_KEY_PWD0			"${SYS_RNWD_NET_DEVICE_KEY_PWD0}"
</#if>
<#if SYS_RNWF_NET_SERVER_NAME0 == "" >
#define SYS_WINCS_NET_SERVER_NAME0				NULL
<#else>
#define SYS_WINCS_NET_SERVER_NAME0				"${SYS_RNWF_NET_SERVER_NAME0}"
</#if>		
<#if SYS_RNWF_NET_DOMAIN_NAME_VERIFY0 == true >
#define SYS_WINCS_NET_DOMAIN_NAME_VERIFY0        1
#define SYS_WINCS_NET_DOMAIN_NAME0				"${SYS_RNWF_NET_DOMAIN_NAME0}"
<#else>
#define SYS_WINCS_NET_DOMAIN_NAME_VERIFY0        0
#define SYS_WINCS_NET_DOMAIN_NAME0				""
</#if>
<#else>
#define SYS_WINCS_TLS_ENABLE0					0
</#if>

<#if SYS_RNWF_NET_NO_OF_SOCKS == 2>

<#if SYS_RNWF_NET_MODE1 == "SERVER">
#define SYS_WINCS_NET_BIND_TYPE1					SYS_WINCS_BIND_LOCAL
<#elseif SYS_RNWF_NET_MODE1 == "CLIENT">
#define SYS_WINCS_NET_BIND_TYPE1					SYS_WINCS_BIND_REMOTE 
</#if>
<#if SYS_RNWF_NET_SOCK_TYPE1 == "UDP">
#define SYS_WINCS_NET_SOCK_TYPE1					SYS_WINCS_SOCK_UDP
<#elseif SYS_RNWF_NET_SOCK_TYPE1 == "TCP">
#define SYS_WINCS_NET_SOCK_TYPE1					SYS_WINCS_SOCK_TCP 
</#if>
<#if SYS_RNWF_NET_SOCK_IP_TYPE1 == "IPv4">
#define SYS_WINCS_NET_SOCK_TYPE_IPv4_1              4
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_LOCAL1         0
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_GLOBAL1        0
<#elseif SYS_RNWF_NET_SOCK_IP_TYPE1 == "IPv6 Local">
#define SYS_WINCS_NET_SOCK_TYPE_IPv4_1              0
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_LOCAL1         6
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_GLOBAL1        0
<#elseif SYS_RNWF_NET_SOCK_IP_TYPE1 == "IPv6 Global">
#define SYS_WINCS_NET_SOCK_TYPE_IPv4_1              0
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_LOCAL1         0
#define SYS_WINCS_NET_SOCK_TYPE_IPv6_GLOBAL1        6
</#if>
<#if SYS_RNWF_NET_MODE0 == "CLIENT">
#define SYS_WINCS_NET_SOCK_SERVER_ADDR1             "${SYS_RNWF_NET_SOCK_IP_ADDR1}"
</#if>
#define SYS_WINCS_NET_SOCK_PORT1				    ${SYS_RNWF_NET_SOCK_PORT1}

<#if SYS_RNWF_NET_ENABLE_TLS1 == true >
#define SYS_WINCS_TLS_ENABLE1					1
#define SYS_WINCS_NET_ROOT_CERT1					"${SYS_RNWF_NET_ROOT_CERT1}"

<#if SYS_RNWF_NET_DEVICE_KEY1 == "" >
#define SYS_WINCS_NET_DEVICE_KEY1				    NULL
<#else>
#define SYS_WINCS_NET_DEVICE_KEY1				    "${SYS_RNWF_NET_DEVICE_KEY1}"
</#if>

<#if SYS_RNWD_NET_DEVICE_KEY_PWD1 == "" >
#define SYS_WINCS_NET_DEVICE_KEY_PWD1			    NULL
<#else>
#define SYS_WINCS_NET_DEVICE_KEY_PWD1			    "${SYS_RNWD_NET_DEVICE_KEY_PWD1}"
</#if>

<#if SYS_RNWF_NET_SERVER_NAME1 == "" >
#define SYS_WINCS_NET_SERVER_NAME1				    NULL
<#else>
#define SYS_WINCS_NET_SERVER_NAME1				    "${SYS_RNWF_NET_SERVER_NAME1}"
</#if>		

<#if SYS_RNWF_NET_DOMAIN_NAME_VERIFY1 == true >
#define SYS_WINCS_NET_DOMAIN_NAME_VERIFY1        1
#define SYS_WINCS_NET_DOMAIN_NAME1				    "${SYS_RNWF_NET_DOMAIN_NAME1}"
<#else>
#define SYS_WINCS_NET_DOMAIN_NAME_VERIFY1            0
#define SYS_WINCS_NET_DOMAIN_NAME1				    ""
</#if>

<#else>
#define SYS_WINCS_TLS_ENABLE1					    0
</#if>
</#if>

</#if>
<#if SYS_RNWF_NET_DEBUG_LOGS == true>
#define SYS_WINCS_NET_DEBUG_LOGS                    1
</#if>

#define SYS_WINCS_NET_SockCallbackHandler  	     ${SYS_RNWF_NET_SOCKET_CALLBACK_HANDLER}